version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: de-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: de_workbench

    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend

    container_name: de-backend

    ports:
      - "8000:8000"

    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend

    container_name: de-frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend