import { MarkerType } from "reactflow";

const edgeStyle = {
  stroke: "#3b82f6",
  strokeWidth: 2,
};

const markerEnd = {
  type: MarkerType.ArrowClosed,
  width: 18,
  height: 18,
  color: "#3b82f6",
};

const roadmapEdges = [
  {
    id: "python-sql",
    source: "python",
    target: "sql",
    type: "smoothstep",
    animated: true,
    style: edgeStyle,
    markerEnd,
  },
  {
    id: "sql-postgresql",
    source: "sql",
    target: "postgresql",
    type: "smoothstep",
    animated: true,
    style: edgeStyle,
    markerEnd,
  },
  {
    id: "postgresql-warehouse",
    source: "postgresql",
    target: "warehouse",
    type: "smoothstep",
    animated: true,
    style: edgeStyle,
    markerEnd,
  },
  {
    id: "warehouse-etl",
    source: "warehouse",
    target: "etl",
    type: "smoothstep",
    animated: true,
    style: edgeStyle,
    markerEnd,
  },
  {
    id: "etl-airflow",
    source: "etl",
    target: "airflow",
    type: "smoothstep",
    animated: true,
    style: edgeStyle,
    markerEnd,
  },
  {
    id: "airflow-pyspark",
    source: "airflow",
    target: "pyspark",
    type: "smoothstep",
    animated: true,
    style: edgeStyle,
    markerEnd,
  },
  {
    id: "pyspark-delta",
    source: "pyspark",
    target: "delta",
    type: "smoothstep",
    animated: true,
    style: edgeStyle,
    markerEnd,
  },
  {
    id: "delta-adls",
    source: "delta",
    target: "adls",
    type: "smoothstep",
    animated: true,
    style: edgeStyle,
    markerEnd,
  },
  {
    id: "adls-adf",
    source: "adls",
    target: "adf",
    type: "smoothstep",
    animated: true,
    style: edgeStyle,
    markerEnd,
  },
  {
    id: "adf-databricks",
    source: "adf",
    target: "databricks",
    type: "smoothstep",
    animated: true,
    style: edgeStyle,
    markerEnd,
  },
  {
    id: "databricks-synapse",
    source: "databricks",
    target: "synapse",
    type: "smoothstep",
    animated: true,
    style: edgeStyle,
    markerEnd,
  },
  {
    id: "synapse-azuresql",
    source: "synapse",
    target: "azure-sql",
    type: "smoothstep",
    animated: true,
    style: edgeStyle,
    markerEnd,
  },
  {
    id: "azuresql-devops",
    source: "azure-sql",
    target: "devops",
    type: "smoothstep",
    animated: true,
    style: edgeStyle,
    markerEnd,
  },
  {
    id: "devops-kafka",
    source: "devops",
    target: "kafka",
    type: "smoothstep",
    animated: true,
    style: edgeStyle,
    markerEnd,
  },
  {
    id: "kafka-production",
    source: "kafka",
    target: "production",
    type: "smoothstep",
    animated: true,
    style: edgeStyle,
    markerEnd,
  },
];

export default roadmapEdges;